version: "3.7"
 
services: 
  syslogserver-tls: 
    build: rsyslog/ 
    hostname: rsyslog-server.com 
    container_name: rsyslog 
    restart: always
    volumes: 
      - "/var/logs:/var/log" 
    ports: 
      - 10514:10514
    cap_add:
      - SYSLOG