version: "3.7"
 
services: 
  syslogserver-tls: 
    build: rsyslog/ 
    hostname: ${SERVER_LOCAL} 
    container_name: rsyslog-tls
    restart: always
    volumes: 
      - "/var/logs:/var/log" 
    ports: 
      - 10514:10514
    cap_add:
      - SYSLOG