version: "3.7"
 
services: 
  syslogserver-tls: 
    build: rsyslog/ 
    hostname: ${SERVER_LOCAL} 
    container_name: ${CONTAINER_NAME}
    restart: always
    volumes: 
      - "/var/logs:/var/log"
      - "/etc/pki/rsyslog-docker:/etc/pki/rsyslog" 
    ports: 
      - 10514:10514
    cap_add:
      - SYSLOG