version: "3.7"
 
services: 
  syslogserver-tls: 
    build: rsyslog/ 
    hostname: ${SERVER_LOCAL} 
    container_name: ${CONTAINER_NAME}
    restart: always
    privileged: true
    volumes: 
      - "/var/logs:/var/log"
      - "/etc/rsyslog-docker/:/etc/rsyslog/"
    ports: 
      - ${TLS_PORT_HOST}:${TLS_PORT_CONTAINER}
    cap_add:
      - SYSLOG