version: "3.7"
 
services: 
  syslogserver-tls:
    build:
      context: rsyslog/
      args: #default options for build
        #PATH_CERT: certificates/
        MAX_SESSIONS: ${MAX_SESSIONS}
        TLS_PORT_CONTAINER: ${TLS_PORT_CONTAINER}
        SERVER_CA_PATH: /etc/rsyslog/pki/${CA_CRT_NAME}
        SERVER_CERT_PATH: /etc/rsyslog/pki/${SERVER_LOCAL}.crt.pem
        SERVER_KEY_PATH: /etc/rsyslog/pki/${SERVER_LOCAL}.key.pem
        SERVER_TEMPLATE_PATH: /var/log/agentlogs-tls/%FROMHOST-IP%/%APP-NAME%/%PROGRAMNAME%.log 
    image: ${IMAGE_NAME}:latest
    hostname: ${SERVER_LOCAL} 
    container_name: ${CONTAINER_NAME}
    restart: always
    privileged: true
    environment: #options for production
      MAX_TCP_SESSIONS: 3000 
      TLS_PORT: 10514
      CA_PATH: /etc/rsyslog/pki/ca.crt.pem 
      CERT_PATH: /etc/rsyslog/pki/server.internal.com.crt.pem 
      KEY_PATH: /etc/rsyslog/pki/server.internal.com.key.pem
      TEMPLATE_PATH: /var/log/agentlogs-tls/%FROMHOST-IP%/%APP-NAME%/%PROGRAMNAME%.log
    volumes: 
      - "/var/logs:/var/log"
      - "/etc/rsyslog-docker/:/etc/rsyslog/"
    ports: 
      - ${TLS_PORT_HOST}:${TLS_PORT_CONTAINER}
    cap_add:
      - SYSLOG
  
  cron-app:
    build:  
      context: cron/
      args: #default options for build
        ALPINE_VERSION: ${ALPINE_VERSION}
        ROTATE_DAYS: ${ROTATE_DAYS} 
        DELETE_DAYS: ${DELETE_DAYS}
        PATH_FILES: /var/log/agentlogs-tls/
        PATH_LOG_FILE: /var/log/agentlogs-tls/cron-day.log
        MAX_DEPTH_DIR: ${MAX_DEPTH_DIR}
        MAX_DEPTH_FILES: ${MAX_DEPTH_FILES}
    image: ${CRON_IMAGE_NAME}:latest
    hostname: ${CRON_LOCAL} 
    container_name: ${CRON_LOCAL}
    restart: always
    privileged: true
    environment: #options for production
      AGE_DAYS: 1 
      DEL_DAYS: 14  
      APP_PATH_FILES: /var/log/agentlogs-tls/
      APP_PATH_LOG_FILE: /var/log/agentlogs-tls/cron-day.log
      DEPTH_DIR: 1
      DEPTH_FILES: 2
    volumes: 
      - "/var/logs/agentlogs-tls/:/var/log/agentlogs-tls/"
    depends_on:
      - syslogserver-tls