version: "3.7"
 
services: 
  syslogserver-tls: 
    build:
      context: rsyslog/
      args:
        PATH_CONFIG: /config/
        PATH_CERT: /certificates/
    image: ${IMAGE_NAME}
    hostname: ${SERVER_LOCAL} 
    container_name: ${CONTAINER_NAME}
    restart: always
    privileged: true
    volumes: 
      - "/var/logs:/var/log"
      - "/etc/rsyslog-docker/:/etc/rsyslog/"
    ports: 
      - ${TLS_PORT_HOST}:${TLS_PORT_CONTAINER}
    cap_add:
      - SYSLOG
  
  cron-app:
    build:  
      context: cron/
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        ROTATE_DAYS: 1 
        DELETE_DAYS: 7
        PATH_FILES: /var/log/agentlogs-tls/
        PATH_LOG_FILE: /var/log/agentlogs-tls/cron-day.log
    image: ${CRON_IMAGE_NAME}
    hostname: ${CRON_LOCAL} 
    container_name: ${CRON_LOCAL}
    restart: always
    privileged: true
    environment:
      AGE_DAYS: 1 
      DEL_DAYS: 14  
      APP_PATH_FILES: /var/log/agentlogs-tls/
      APP_PATH_LOG_FILE: /var/log/agentlogs-tls/cron-day.log
    volumes: 
      - "/var/logs/agentlogs-tls/:/var/log/agentlogs-tls/"
    depends_on:
      - syslogserver-tls
